on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: simple
      - uses: actions/checkout@v2
      - name: tag major and minor versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          git tag -d ${{ steps.release.outputs.major }} || true
          git tag -d ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git push origin :${{ steps.release.outputs.major }} || true
          git push origin :${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git tag -a ${{ steps.release.outputs.major }} -m "Release ${{ steps.release.outputs.major }}"
          git tag -a ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
          git push origin ${{ steps.release.outputs.major }}
          git push origin ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
