name: Tests
on:
  pull_request:
  push:

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Setting up Java 16
        uses: joschi/setup-jdk@v2
        with:
          java-version: '16' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'
      - name: Making executable gradlew
        run: chmod +x gradlew
      - name: Running test
        run: ./gradlew clean check -i
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'